// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKbi3oSuqJ9GH7BWmM8DqiaaJH-QMYBDU',
    appId: '1:1085360030767:web:4647c67894b521d8fbb2da',
    messagingSenderId: '1085360030767',
    projectId: 'feedforward-3e93d',
    authDomain: 'feedforward-3e93d.firebaseapp.com',
    storageBucket: 'feedforward-3e93d.appspot.com',
    measurementId: 'G-1XZ8GFLQZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsC_Voco5k2A20loEyUdih97Ni03cSxoU',
    appId: '1:1085360030767:android:c60322478f5a49b5fbb2da',
    messagingSenderId: '1085360030767',
    projectId: 'feedforward-3e93d',
    storageBucket: 'feedforward-3e93d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5tgjlqM5vIV192SIYxsnHPpE6SNchfyA',
    appId: '1:1085360030767:ios:1f127da47d310d18fbb2da',
    messagingSenderId: '1085360030767',
    projectId: 'feedforward-3e93d',
    storageBucket: 'feedforward-3e93d.appspot.com',
    iosClientId: '1085360030767-asa11nolu7n1grljft9mmrdntilcgfbd.apps.googleusercontent.com',
    iosBundleId: 'tech.feedforward.feedforward',
  );
}
